<?php
define("HOME", "Home");
define("LOGOUT", "Logout");
define("MAIN_CONF_LIST_TEXT", "Next conference");
define("PLACE", "Location");
define("SPEAKER", "Speaker");
define("SHARE", "Share");
define("SIGNIN", "Sign in");
define("LOGOUT_DESC", "Connect to see the conferences");
define("USERNAME", "Username");
define("PASSWORD", "Password");
define("CONNECT_BUTTON", "Connect");
define("ADMIN", "Administration");
define("TITLE", "Title");
define("HOUR", "Hour");
define("DATE", "Date");
define("DESCRIPTION", "Description");
define("ACTION", "Action");
define("ADD", "Add");
define("ADMIN_DESC_TEXT", "Manage conferences");
define("ADD_DESC_TEXT", "Add a conference");
define("ADD_SUB_DESC_TEXT", "Complete the following fields");
define("SUBMIT", "Submit");
define("EDIT_DESC_TEXT", "Edit a conference");
define("DEL_DESC_TEXT", "Delete a conference");
define("CONFIRM_DEL_U", "The user has been deleted");
define("NO_CONF", "No conference is available");
define("CONFIRM_DEL", "The conference has been deleted");
define("CONFIRM_EDIT_ADD", "Your modifications have been saved");
define("ADMIN_BUTTON", "Administration");
define("DEL_BUTTON", "Delete");
define("EDIT_BUTTON", "Edit");
define("INPUT_ERROR", "Invalid data given");
define("LOGOUT_NOTIF", "You have been disconnected");
define("LOGOUT_ERROR", "An error has occurred");
define("NEXT_LANGUAGE", "Français");
define("LEVEL", "Level");
define("DEL_USER_DESC_TEXT", "Delete a user");
define("ADD_USER_DESC_TEXT", "Add a user");
define("EDIT_USER_DESC_TEXT", "Edit a user");
define("LOGIN_CHECKCHAR_FAILED", "The login must not contain special characters and have a length between 3 and 16 characters");
define("DATA_CHARCHECK_FAILED", "The fields must not contain special characters.");
define("CONNECTED_AS", "Connected as");
?>
