<?php
define("HOME", "Accueil");
define("LOGOUT", "Déconnexion");
define("MAIN_CONF_LIST_TEXT", "Prochaines conférences");
define("PLACE", "Lieu");
define("SPEAKER", "Conférencier");
define("SHARE", "Partager");
define("SIGNIN", "Connexion");
define("LOGOUT_DESC", "Connectez-vous pour voir les conférences");
define("USERNAME", "Nom d'utilisateur");
define("PASSWORD", "Mot de passe");
define("CONNECT_BUTTON", "Connexion");
define("ADMIN", "Administration");
define("TITLE", "Titre");
define("HOUR", "Heure");
define("DESCRIPTION", "Description");
define("ACTION", "Action");
define("ADD", "Ajouter");
define("ADMIN_DESC_TEXT", "Gérez vos conférences");
define("ADD_DESC_TEXT", "Ajoutez votre conférence");
define("ADD_SUB_DESC_TEXT", "Remplissez les champs suivants pour ajouter votre conférence");
define("SUBMIT", "Envoyer");
define("EDIT_DESC_TEXT", "Modifier une conférence");
define("DEL_DESC_TEXT", "Supprimer une conférence");
define("NO_CONF", "Aucune conférence n'est disponible");
define("CONFIRM_DEL", "La conférence a été supprimée");
define("CONFIRM_EDIT_ADD", "Vos modifications ont été enregistrées");
define("ADMIN_BUTTON", "Administration");
define("DEL_BUTTON", "Supprimer");
define("INPUT_ERROR", "Les données saisies ne sont pas valides");
define("LOGOUT_NOTIF", "Vous avez été déconnecté");
define("LOGOUT_ERROR", "Une erreur est survenue");
define("NEXT_LANGUAGE", "English");
define("LEVEL", "Rang");
?>
